import type { CatalogPlace, Place } from "./types";

export const initialPlaces: Place[] = [
  {
    id: "eiffel",
    time: "09:00",
    duration: "1시간 20분",
    title: "에펠탑",
    category: "랜드마크 · 전망",
    note: "샹드마르스에서 천천히 걸어 타워 전망대로 이동해요.",
    emoji: "🗼",
    coords: [48.85837, 2.294481],
    travel: "메트로 18분",
    alternatives: [
      { id: "trocadero", time: "09:00", title: "트로카데로 광장", category: "전망 · 사진", note: "에펠탑 정면 뷰", emoji: "📷", coords: [48.8629, 2.287] },
      { id: "arc", time: "09:20", title: "개선문", category: "랜드마크", note: "샹젤리제 시작점", emoji: "🏛️", coords: [48.8738, 2.295] },
    ],
  },
  {
    id: "flore",
    time: "11:10",
    duration: "1시간",
    title: "카페 드 플로르",
    category: "브런치 · 카페",
    note: "테라스에서 크루아상과 카페 크렘으로 잠깐 쉬어가요.",
    emoji: "☕",
    coords: [48.8541, 2.3325],
    travel: "도보 14분",
    alternatives: [
      { id: "deux-magots", time: "11:10", title: "레 되 마고", category: "브런치 · 카페", note: "생제르맹의 클래식 카페", emoji: "🥐", coords: [48.854, 2.3332] },
      { id: "holybelly", time: "11:30", title: "Holybelly", category: "브런치", note: "팬케이크가 유명한 브런치", emoji: "🥞", coords: [48.8716, 2.3634] },
    ],
  },
  {
    id: "louvre",
    time: "13:20",
    duration: "2시간",
    title: "루브르 박물관",
    category: "미술관 · 전시",
    note: "드농관 중심으로 보고 튈르리 정원까지 이어서 걸어요.",
    emoji: "🖼️",
    coords: [48.8606, 2.3376],
    travel: "메트로 16분",
    alternatives: [
      { id: "orsay", time: "13:20", title: "오르세 미술관", category: "미술관", note: "인상주의 컬렉션", emoji: "🎨", coords: [48.86, 2.3266] },
      { id: "orangerie", time: "13:40", title: "오랑주리 미술관", category: "미술관", note: "모네의 수련 연작", emoji: "🌿", coords: [48.8638, 2.3227] },
    ],
  },
  {
    id: "marais",
    time: "16:20",
    duration: "1시간 30분",
    title: "르 마레",
    category: "거리 · 쇼핑",
    note: "골목 상점과 작은 갤러리를 구경하며 자유롭게 산책해요.",
    emoji: "🛍️",
    coords: [48.8577, 2.3622],
    travel: "메트로 20분",
    alternatives: [
      { id: "canal", time: "16:20", title: "생마르탱 운하", category: "산책", note: "현지 분위기의 운하 산책", emoji: "🌉", coords: [48.8722, 2.365] },
      { id: "palais-royal", time: "16:40", title: "팔레 루아얄", category: "정원 · 건축", note: "조용한 안뜰과 정원", emoji: "🌳", coords: [48.8638, 2.337] },
    ],
  },
  {
    id: "sacre-coeur",
    time: "18:40",
    duration: "1시간 20분",
    title: "사크레쾨르 대성당",
    category: "노을 · 전망",
    note: "몽마르트르 언덕에서 파리의 저녁 풍경을 마무리해요.",
    emoji: "🌇",
    coords: [48.8867, 2.3431],
    alternatives: [
      { id: "montparnasse", time: "18:40", title: "몽파르나스 타워", category: "야경 · 전망", note: "파리 전경 전망대", emoji: "🌃", coords: [48.8421, 2.3219] },
      { id: "seine", time: "19:00", title: "센강 유람선", category: "야경 · 크루즈", note: "강 위에서 보는 파리", emoji: "🛥️", coords: [48.8596, 2.2978] },
    ],
  },
];

export const placeCatalog: CatalogPlace[] = [
  { title: "에펠탑", category: "랜드마크", emoji: "🗼", coords: [48.85837, 2.294481], city: "파리", country: "프랑스" },
  { title: "루브르 박물관", category: "미술관", emoji: "🖼️", coords: [48.8606, 2.3376], city: "파리", country: "프랑스" },
  { title: "오르세 미술관", category: "미술관", emoji: "🎨", coords: [48.86, 2.3266], city: "파리", country: "프랑스" },
  { title: "카페 드 플로르", category: "카페", emoji: "☕", coords: [48.8541, 2.3325], city: "파리", country: "프랑스" },
  { title: "사크레쾨르 대성당", category: "랜드마크", emoji: "🌇", coords: [48.8867, 2.3431], city: "파리", country: "프랑스" },
  { title: "콜로세움", category: "유적지", emoji: "🏟️", coords: [41.8902, 12.4922], city: "로마", country: "이탈리아" },
  { title: "트레비 분수", category: "랜드마크", emoji: "⛲", coords: [41.9009, 12.4833], city: "로마", country: "이탈리아" },
  { title: "사그라다 파밀리아", category: "건축", emoji: "⛪", coords: [41.4036, 2.1744], city: "바르셀로나", country: "스페인" },
  { title: "대영박물관", category: "박물관", emoji: "🏛️", coords: [51.5194, -0.127], city: "런던", country: "영국" },
  { title: "타워 브리지", category: "랜드마크", emoji: "🌉", coords: [51.5055, -0.0754], city: "런던", country: "영국" },
  { title: "센소지", category: "사원", emoji: "🏮", coords: [35.7148, 139.7967], city: "도쿄", country: "일본" },
  { title: "시부야 스크램블", category: "도시 명소", emoji: "🚦", coords: [35.6595, 139.7005], city: "도쿄", country: "일본" },
  { title: "브루클린 브리지", category: "랜드마크", emoji: "🌉", coords: [40.7061, -73.9969], city: "뉴욕", country: "미국" },
  { title: "센트럴 파크", category: "공원", emoji: "🌳", coords: [40.7829, -73.9654], city: "뉴욕", country: "미국" },
  { title: "벨렝탑", category: "랜드마크", emoji: "🏰", coords: [38.6916, -9.216], city: "리스본", country: "포르투갈" },
];
